// Code generated by entc, DO NOT EDIT.

package label

import (
	"entrds/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// YearEstablished applies equality check predicate on the "year_established" field. It's identical to YearEstablishedEQ.
func YearEstablished(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYearEstablished), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Label {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Label {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// YearEstablishedEQ applies the EQ predicate on the "year_established" field.
func YearEstablishedEQ(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedNEQ applies the NEQ predicate on the "year_established" field.
func YearEstablishedNEQ(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedIn applies the In predicate on the "year_established" field.
func YearEstablishedIn(vs ...int) predicate.Label {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYearEstablished), v...))
	})
}

// YearEstablishedNotIn applies the NotIn predicate on the "year_established" field.
func YearEstablishedNotIn(vs ...int) predicate.Label {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Label(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYearEstablished), v...))
	})
}

// YearEstablishedGT applies the GT predicate on the "year_established" field.
func YearEstablishedGT(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedGTE applies the GTE predicate on the "year_established" field.
func YearEstablishedGTE(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedLT applies the LT predicate on the "year_established" field.
func YearEstablishedLT(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedLTE applies the LTE predicate on the "year_established" field.
func YearEstablishedLTE(v int) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYearEstablished), v))
	})
}

// YearEstablishedIsNil applies the IsNil predicate on the "year_established" field.
func YearEstablishedIsNil() predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldYearEstablished)))
	})
}

// YearEstablishedNotNil applies the NotNil predicate on the "year_established" field.
func YearEstablishedNotNil() predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldYearEstablished)))
	})
}

// HasIndividualArtists applies the HasEdge predicate on the "individual_artists" edge.
func HasIndividualArtists() predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IndividualArtistsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, IndividualArtistsTable, IndividualArtistsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIndividualArtistsWith applies the HasEdge predicate on the "individual_artists" edge with a given conditions (other predicates).
func HasIndividualArtistsWith(preds ...predicate.Artist) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IndividualArtistsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, IndividualArtistsTable, IndividualArtistsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBands applies the HasEdge predicate on the "bands" edge.
func HasBands() predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BandsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, BandsTable, BandsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBandsWith applies the HasEdge predicate on the "bands" edge with a given conditions (other predicates).
func HasBandsWith(preds ...predicate.Band) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BandsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, BandsTable, BandsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Label) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Label) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Label) predicate.Label {
	return predicate.Label(func(s *sql.Selector) {
		p(s.Not())
	})
}
