// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entrds/ent/album"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Album is the model entity for the Album schema.
type Album struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ReleaseYear holds the value of the "release_year" field.
	ReleaseYear int `json:"release_year,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlbumQuery when eager-loading is set.
	Edges AlbumEdges `json:"edges"`
}

// AlbumEdges holds the relations/edges for other nodes in the graph.
type AlbumEdges struct {
	// Band holds the value of the band edge.
	Band []*Band `json:"band,omitempty"`
	// Artist holds the value of the artist edge.
	Artist []*Artist `json:"artist,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BandOrErr returns the Band value or an error if the edge
// was not loaded in eager-loading.
func (e AlbumEdges) BandOrErr() ([]*Band, error) {
	if e.loadedTypes[0] {
		return e.Band, nil
	}
	return nil, &NotLoadedError{edge: "band"}
}

// ArtistOrErr returns the Artist value or an error if the edge
// was not loaded in eager-loading.
func (e AlbumEdges) ArtistOrErr() ([]*Artist, error) {
	if e.loadedTypes[1] {
		return e.Artist, nil
	}
	return nil, &NotLoadedError{edge: "artist"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Album) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case album.FieldID, album.FieldReleaseYear:
			values[i] = new(sql.NullInt64)
		case album.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Album", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Album fields.
func (a *Album) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case album.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case album.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case album.FieldReleaseYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field release_year", values[i])
			} else if value.Valid {
				a.ReleaseYear = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryBand queries the "band" edge of the Album entity.
func (a *Album) QueryBand() *BandQuery {
	return (&AlbumClient{config: a.config}).QueryBand(a)
}

// QueryArtist queries the "artist" edge of the Album entity.
func (a *Album) QueryArtist() *ArtistQuery {
	return (&AlbumClient{config: a.config}).QueryArtist(a)
}

// Update returns a builder for updating this Album.
// Note that you need to call Album.Unwrap() before calling this method if this Album
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Album) Update() *AlbumUpdateOne {
	return (&AlbumClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Album entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Album) Unwrap() *Album {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Album is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Album) String() string {
	var builder strings.Builder
	builder.WriteString("Album(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", name=")
	builder.WriteString(a.Name)
	builder.WriteString(", release_year=")
	builder.WriteString(fmt.Sprintf("%v", a.ReleaseYear))
	builder.WriteByte(')')
	return builder.String()
}

// Albums is a parsable slice of Album.
type Albums []*Album

func (a Albums) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
