// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entrds/ent/label"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Label is the model entity for the Label schema.
type Label struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// YearEstablished holds the value of the "year_established" field.
	YearEstablished int `json:"year_established,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LabelQuery when eager-loading is set.
	Edges LabelEdges `json:"edges"`
}

// LabelEdges holds the relations/edges for other nodes in the graph.
type LabelEdges struct {
	// IndividualArtists holds the value of the individual_artists edge.
	IndividualArtists []*Artist `json:"individual_artists,omitempty"`
	// Bands holds the value of the bands edge.
	Bands []*Band `json:"bands,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// IndividualArtistsOrErr returns the IndividualArtists value or an error if the edge
// was not loaded in eager-loading.
func (e LabelEdges) IndividualArtistsOrErr() ([]*Artist, error) {
	if e.loadedTypes[0] {
		return e.IndividualArtists, nil
	}
	return nil, &NotLoadedError{edge: "individual_artists"}
}

// BandsOrErr returns the Bands value or an error if the edge
// was not loaded in eager-loading.
func (e LabelEdges) BandsOrErr() ([]*Band, error) {
	if e.loadedTypes[1] {
		return e.Bands, nil
	}
	return nil, &NotLoadedError{edge: "bands"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Label) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case label.FieldID, label.FieldYearEstablished:
			values[i] = new(sql.NullInt64)
		case label.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Label", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Label fields.
func (l *Label) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case label.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case label.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				l.Name = value.String
			}
		case label.FieldYearEstablished:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year_established", values[i])
			} else if value.Valid {
				l.YearEstablished = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryIndividualArtists queries the "individual_artists" edge of the Label entity.
func (l *Label) QueryIndividualArtists() *ArtistQuery {
	return (&LabelClient{config: l.config}).QueryIndividualArtists(l)
}

// QueryBands queries the "bands" edge of the Label entity.
func (l *Label) QueryBands() *BandQuery {
	return (&LabelClient{config: l.config}).QueryBands(l)
}

// Update returns a builder for updating this Label.
// Note that you need to call Label.Unwrap() before calling this method if this Label
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Label) Update() *LabelUpdateOne {
	return (&LabelClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Label entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Label) Unwrap() *Label {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Label is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Label) String() string {
	var builder strings.Builder
	builder.WriteString("Label(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", name=")
	builder.WriteString(l.Name)
	builder.WriteString(", year_established=")
	builder.WriteString(fmt.Sprintf("%v", l.YearEstablished))
	builder.WriteByte(')')
	return builder.String()
}

// Labels is a parsable slice of Label.
type Labels []*Label

func (l Labels) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
