// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Album is the predicate function for album builders.
type Album func(*sql.Selector)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Band is the predicate function for band builders.
type Band func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)
